version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask-ml-container
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - my_network

  redis:
    image: "redis:latest"
    container_name: redis-db
    ports:
      - "6379:6379"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
